/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_hackday_android_extract_gif_FFmpegUtils */

#ifndef _Included_com_naver_hackday_android_extract_gif_FFmpegUtils
#define _Included_com_naver_hackday_android_extract_gif_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_naver_hackday_android_extract_gif_FFmpegUtils
 * Method:    runFFmpeg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_naver_hackday_android_1extract_1gif_FFmpegUtils_runFFmpeg
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
